# Generated by Django 4.2.3 on 2023-08-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='news/images/iq1.jpg', upload_to='users/images'),
        ),
    ]
